### ISSUE TITLE
Unknown Item Error when loading a converted Gen-XX Save 

### ISSUE THREAD

**Issue by Xerahawke** [mineminemine/MHXXSaveEditor#2]
Tried using multiple save for MHXX with this editor which returns with an unknown item error message for all items in save and then it crashes.

[system.zip](https://github.com/mineminemine/MHXXSaveEditor/files/1500338/system.zip)

**Comment by mineminemine** [comment]
Did you remove any DLC MHGen equipment before converting it to MHXX?
Cause you need to remove those before converting the save file to MHXX as MHGen DLCs will not load in MHXX.

Edit: Okay, I checked your save file and it seems that its broken?
Did you somehow break the file when converting it?
Cause loading the save file in-game crashes my console.

**Comment by Xerahawke** [comment]
The save file works in mhxx. I haven't got any dlc equipment I believe.

**Comment by mineminemine** [comment]
Are you sure it's working?
I tried loading your save file and it crashes for me in-game.

I looked into your save file and it seems like its not a MHXX save file? Cause it contained some weird gibberish that's not supposed to be there. 
Did you somehow corrupted the save file when extracting it from the game?
Are you using Checkpoint? Or JKSM?

**Comment by Xerahawke** [comment]
I'm using it on MHXX fine :s I copied it via checkpoint twice just to be
sure and both errored.

**Comment by mineminemine** [comment]
Can you try using [JKSM](https://gbatemp.net/threads/release-jks-savemanager-homebrew-cia-save-manager.413143/) instead?

**Comment by Xerahawke** [comment]
Okay I will try it when I'm back in a few hours.

**Comment by mineminemine** [comment]
And if using JKSM to extract the save file still crashes, could you upload your save file here again? Thanks.

**Comment by Xerahawke** [comment]
Not a problem I will do.

**Comment by Xerahawke** [comment]
Okay I tested with JKSM and it works perfectly.
So checkpoint was causing the issue.
