### ISSUE TITLE
about Wiki guild card structure specification

### ISSUE THREAD

**Issue by xinyuwufei** [mineminemine/MHXXSaveEditor#3]
based on the new release of chinese language patch for MHGU(international verion of MHXX)

the maximum lengh to set a name with full-width forms (see ref. below) or mixed form is 6
and the maximum lengh to set a name with half-width forms is 10

so I think the following spec should be

From：

## Guild Card

Offset (Hex)|Size|Description
------------|----|-----------
0000|12|Name (UTF-16) ??
000C|12|Unknown

To：

## Guild Card

Offset (Hex)|Size|Description
------------|----|-----------
0000|12|Name  (UTF-16) (if fullwidth forms or mixed forms)
000C|12|Name extend  (UTF-16) (if Halfwidth only)

ref:
https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms
![mhgu_name_regulation](https://user-images.githubusercontent.com/6299086/47778589-89877e00-dd3a-11e8-9405-0276a36a29dc.jpg)

**Comment by mineminemine** [comment]
Edited wiki page, thank you!
